<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Save' => 'ذخیره',
    'delete' => 'حذف',
    'update' => 'ویرایش',
    'Update' => 'ویرایش',
    'Delete' => 'حذف',
    'ID' => 'شناسه',
    'Title' => 'عنوان',
    'Description' => 'توضیحات',
    'Search Model Class' => 'کلاس جستجو',
    'Search Model Method' => 'کلاس متد',
    'Status' => 'وضعیت',
    'Deleted At' => 'تاریخ حذف',
    'Search Model Run Result View' => 'صفحه نمایش مدل جستجو',
    'Range Type' => 'دوره نمایش',
    'Visibility' => 'قابل نمایش',
    'Updated At' => 'آخرین آپدیت',
    'Created At' => 'تاریخ ایجاد',
    'Updated By' => 'آپدیت توسط',
    'Created By' => 'ایجاد توسط',
    'Are you sure you want to delete this item?' => 'آیا از حذف این مورد اطمینان دارید؟',

    'Create Report Widget' => 'ایجاد ویجت',
    'Save As Report Widget' => 'ایجاد ویجت',
    'Saved successfully' => 'با موفقیت ذخیره شد',
    'Report Widgets' => 'ویجت‌ها',
    'Update Report Widget: {name}' => 'ویرایش ویجت: {name}',

    'Daily' => 'روزانه',
    'Monthly' => 'ماهانه',
    'visibility' => 'نمایش',
    'invisibility' => 'غیر قابل نمایش',
    'Public' => 'عمومی',
    'Private' => 'خصوصی',
    'Active' => 'فعال',
    'Deleted' => 'حذف شده',
    'InActive' => 'غیرفعال',
    'Search' => 'جستجو',
    'Reset' => 'ریست',

    'add widget' => 'افزودن ویجت',
    'attribute' => 'ویژگی',
    'value' => 'مقدار',

    'Report Model Classes' => 'مدل کلاس های سیستم',
    'Create Report Model Class' => 'ایجاد مدل کلاس',
    'Update Report Model Class: {name}' => 'ویرایش مدل کلاس: {name}',
    'create' => 'ایجاد',

    'Select Status' => 'انتخاب وضعیت',
    'Select RANGE' => 'انتخاب دوره',

    'Report Widget Field Format' => 'نوع نمایش فیلد',
    'Number' => 'عدد',
    'Currency' => 'مبلغ',
    'Success' => 'موفق',
    'run all widget' => 'اجرای تمام ویجت‌ها',
    'run' => 'اجرا',
    'Select widget' => 'انتخاب ویجت',
    'Widget' => 'ویجت',
    'Report Widget Field' => 'فیلد نمایش  ویجت',
    'Show' => 'نمایش',
    '{modelTitle} data is invalid' => ' دیتای ارسالی ویجت {modelTitle} نامعتبر است',
    'The {env_parameter} parameter is not set, add the parameter in the env file of the project.' => 'پارامتر {env_parameter} تنظیم نشده است، پارامتر را در فایل env پروژه اضافه نمایید.',


];